name: techblog_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.6
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  validators: ^3.0.0
  get: ^4.6.6
  share_plus: ^9.0.0
  url_launcher: ^6.3.0
  dio: ^5.5.0+1
  cached_network_image: ^3.3.1
  flutter_widget_from_html: ^0.15.1
  get_storage: ^2.1.1
  file_picker: ^8.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

flutter_gen:
  integrations:
    flutter_svg: true

fonts:
  - family: Dana
    fonts:
      - asset: assets/fonts/bold.ttf
        weight: 700
      - asset: assets/fonts/regular.ttf
        weight: 300
